### PR TITLE
Runs with Python3.8

### PR DESCRIPTION
**Pull request by karstenw**
Just the few changes to make it run.

### CODE REVIEW

**Comment by skymandr** [comment]
Oh wow! Thank you so much! I just lamented the fact that I can never find the time to do this to a friend yesterday. I'll have a look at the PR over the weekend.

**Comment by skymandr** [comment]
This looks good, and works fine for me as well. I'd be happy to merge it, but I can see you are still adding stuff. If you tell me when you're done I'll merge this with main.

**Comment by karstenw** [comment]
Two of the additional commits convert the "demo" folder to py 3.8.

One adds a config for a larger screen.

For my part I am done

**Comment by karstenw** [comment]
I think I hit the wrong button.

**Pull request merged**
